# Generated by Django 5.1.15 on 2026-02-01 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='playable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=50)),
                ('star', models.CharField(max_length=5)),
                ('turf', models.CharField(choices=[('G', 'G'), ('F', 'F'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], default='G', max_length=1)),
                ('dirt', models.CharField(choices=[('G', 'G'), ('F', 'F'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], default='G', max_length=1)),
                ('short', models.CharField(choices=[('G', 'G'), ('F', 'F'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], default='G', max_length=1)),
                ('mile', models.CharField(choices=[('G', 'G'), ('F', 'F'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], default='G', max_length=1)),
                ('medium', models.CharField(choices=[('G', 'G'), ('F', 'F'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], default='G', max_length=1)),
                ('long', models.CharField(choices=[('G', 'G'), ('F', 'F'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], default='G', max_length=1)),
                ('front', models.CharField(choices=[('G', 'G'), ('F', 'F'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], default='G', max_length=1)),
                ('pace', models.CharField(choices=[('G', 'G'), ('F', 'F'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], default='G', max_length=1)),
                ('late', models.CharField(choices=[('G', 'G'), ('F', 'F'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], default='G', max_length=1)),
                ('end', models.CharField(choices=[('G', 'G'), ('F', 'F'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], default='G', max_length=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(choices=[('R', 'R'), ('SR', 'SR'), ('SSR', 'SSR')], default='SSR', max_length=3)),
                ('type', models.CharField(choices=[('Sp', 'Speed'), ('St', 'Stamina'), ('Pw', 'Power'), ('Gt', 'Gut'), ('Wt', 'Wit'), ('P', 'Pal'), ('Ps', 'Pal-group')], default='Ps', max_length=2)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='skill_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('playable', 'playable'), ('support', 'support')], default='playable', max_length=10)),
                ('playable_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.playable')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.skill')),
                ('support_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.support')),
            ],
        ),
    ]
