# Generated by Django 5.1.15 on 2026-01-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='rarity',
            field=models.CharField(choices=[('R', 'R'), ('SR', 'SR'), ('SSR', 'SSR')], default='SSR', max_length=3),
        ),
    ]
