# Generated by Django 5.1.15 on 2026-01-09 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_variant_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='connecter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_connecter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.variant')),
                ('skill_connecter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.skill')),
            ],
        ),
    ]
