# Generated by Django 5.1.15 on 2026-01-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_skill_connecter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connecter',
            old_name='skill_connecter',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='connecter',
            old_name='variant_connecter',
            new_name='variant',
        ),
        migrations.AddField(
            model_name='skill',
            name='aptitude',
            field=models.CharField(choices=[('T', 'Turf'), ('D', 'Dirt'), ('B', 'Both')], default='Both', max_length=10),
        ),
        migrations.AddField(
            model_name='skill',
            name='distance',
            field=models.CharField(choices=[('S', 'Short'), ('M', 'Mile'), ('Me', 'Medium'), ('L', 'Long'), ('A', 'All')], default='All', max_length=10),
        ),
        migrations.AddField(
            model_name='skill',
            name='strategy',
            field=models.CharField(choices=[('F', 'Front'), ('P', 'Pace'), ('L', 'Late'), ('E', 'End'), ('A', 'All')], default='All', max_length=10),
        ),
    ]
