# Generated by Django 5.1.15 on 2026-01-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_rename_skill_connecter_connecter_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='type',
            field=models.CharField(choices=[('play', 'playable'), ('speed', 'Speed'), ('power', 'Power'), ('stamina', 'Stamina'), ('wit', 'Wit'), ('gut', 'Gut'), ('pal', 'Pal')], default='playable', max_length=10),
        ),
    ]
